// ─── Varfarin Etkileşim Rehberi ───────────────────────────────────────
// Kaynak: CHEST 2012, Stockley's Drug Interactions, UpToDate

export const INTERACTIONS = [
  // ─── İLAÇLAR — INR ARTTIRANLAR ───────────────────────────────────
  {
    name: "Flukonazol",
    aliases: ["diflucan"],
    type: "drug",
    direction: "increase",
    severity: "major",
    mechanism: "CYP2C9 inhibitörü",
    note: "INR %50–200 artabilir. Doz %25–50 azaltılmalı, sık INR izlemi gerekli.",
  },
  {
    name: "Metronidazol",
    aliases: ["flagyl"],
    type: "drug",
    direction: "increase",
    severity: "major",
    mechanism: "CYP2C9 + CYP3A4 inhibitörü",
    note: "INR belirgin artar. 3–5 gün içinde INR kontrolü yapılmalı.",
  },
  {
    name: "Kotrimoksazol (TMP-SMX)",
    aliases: ["bactrim", "trimetoprim", "sulfametoksazol"],
    type: "drug",
    direction: "increase",
    severity: "major",
    mechanism: "CYP2C9 inhibisyonu + vitamin K üretimini baskılar",
    note: "INR ikiye katlanabilir. Alternatif antibiyotik tercih edin ya da doz %25–50 azaltın.",
  },
  {
    name: "Amiodaron",
    aliases: ["cordarone"],
    type: "drug",
    direction: "increase",
    severity: "major",
    mechanism: "CYP2C9 ve CYP1A2 inhibitörü; uzun yarı ömür",
    note: "Etki başlangıcı yavaş (haftalar), doz %30–50 azaltılmalı. Kesilince de haftalarca izlem gerekir.",
  },
  {
    name: "Klaritromisin",
    aliases: ["klacid"],
    type: "drug",
    direction: "increase",
    severity: "major",
    mechanism: "CYP3A4 inhibitörü",
    note: "Tedavi süresince ve bitiminden 3–5 gün sonra INR kontrolü.",
  },
  {
    name: "Eritromisin",
    aliases: [],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "CYP3A4 inhibitörü",
    note: "INR artabilir. Mümkünse alternatif antibiyotik, değilse sık izlem.",
  },
  {
    name: "Siprofloksasin",
    aliases: ["cipro"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "CYP1A2 inhibitörü",
    note: "INR %20–30 artabilir. Diğer kinolon antibiyotikler de benzer etki gösterebilir.",
  },
  {
    name: "Levofloksasin",
    aliases: ["tavanic"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "Mekanizma tam açık değil; muhtemelen bağırsak florası",
    note: "INR artabilir; izlem önerilir.",
  },
  {
    name: "Aspirin",
    aliases: ["asetilsalisilik asit", "asa"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "Antiplatelet etki + GİS mukoza hasarı",
    note: "Kanama riski artar. Endikasyon (ACS, stent) varsa düşük doz (≤100 mg) kabul edilebilir; gereksiz kullanımdan kaçının.",
  },
  {
    name: "İbuprofen",
    aliases: ["advil", "brufen"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "NSAID; GİS kanama + antiplatelet",
    note: "Tüm NSAİİ'lerden kaçının. Ağrı için parasetamol tercih edin (≤2 g/gün).",
  },
  {
    name: "Naproksen",
    aliases: ["naprosyn"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "NSAID; GİS kanama riski",
    note: "Kronik kullanımdan kaçının.",
  },
  {
    name: "Diklofenak",
    aliases: ["voltaren"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "NSAID; GİS kanama riski",
    note: "Kullanılacaksa kısa süreli, en düşük doz ve mide koruyucu ile.",
  },
  {
    name: "Fluoksetin",
    aliases: ["prozac"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "CYP2C9 inhibitörü",
    note: "INR %10–30 artabilir. Başlangıçta ve doz değişikliğinde izlem.",
  },
  {
    name: "Sertralin",
    aliases: ["zoloft"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "Zayıf CYP2C9 inhibisyonu + antiplatelet",
    note: "Hafif INR artışı; izlem önerilir.",
  },
  {
    name: "Fenofibrat",
    aliases: ["lipanthyl"],
    type: "drug",
    direction: "increase",
    severity: "moderate",
    mechanism: "CYP2C9 inhibitörü",
    note: "Kronik kullanımda INR %20–50 artabilir; varfarin dozunu azaltın.",
  },
  {
    name: "Statinler (genel)",
    aliases: ["simvastatin", "atorvastatin", "rosuvastatin", "fluvastatin"],
    type: "drug",
    direction: "increase",
    severity: "minor",
    mechanism: "Fluvastatin > diğerleri; CYP2C9 inhibisyonu",
    note: "Fluvastatin ve rosuvastatin daha belirgin. Başlangıçta INR kontrolü yeterli.",
  },
  {
    name: "Omeprazol",
    aliases: ["losec", "prilosec"],
    type: "drug",
    direction: "increase",
    severity: "minor",
    mechanism: "Zayıf CYP2C19 inhibisyonu",
    note: "Klinik etki genellikle minimal; özellikle yüksek dozda izlem.",
  },
  {
    name: "Parasetamol",
    aliases: ["asetaminofen", "panadol", "parol"],
    type: "drug",
    direction: "increase",
    severity: "minor",
    mechanism: "Muhtemelen K vitamini döngüsünü etkiler",
    note: "Günde 2 g altı genellikle güvenli. >2 g/gün uzun süreli kullanımda INR artabilir.",
  },
  // ─── İLAÇLAR — INR AZALTANLAR ────────────────────────────────────
  {
    name: "Rifampisin",
    aliases: ["rifadin"],
    type: "drug",
    direction: "decrease",
    severity: "major",
    mechanism: "Güçlü CYP2C9, 3A4, 1A2 indüktörü",
    note: "INR 2–3 kat düşebilir. Varfarin dozu 2–3 kat artırılmalı; kesilince hızla geri döner, dikkat!",
  },
  {
    name: "Karbamazepin",
    aliases: ["tegretol"],
    type: "drug",
    direction: "decrease",
    severity: "major",
    mechanism: "CYP3A4 ve CYP2C9 indüktörü",
    note: "INR belirgin düşer. Başlangıç, doz değişikliği ve kesişte INR takibi.",
  },
  {
    name: "Fenitoin",
    aliases: ["dilantin"],
    type: "drug",
    direction: "decrease",
    severity: "major",
    mechanism: "CYP2C9 indüktörü (başlangıçta inhibisyon da yapabilir)",
    note: "Karmaşık etkileşim; dikkatli izlem gerekli.",
  },
  {
    name: "Fenobarbital",
    aliases: ["luminal"],
    type: "drug",
    direction: "decrease",
    severity: "moderate",
    mechanism: "CYP indüktörü",
    note: "INR azalabilir. Başlangıç ve doz değişikliğinde izlem.",
  },
  {
    name: "Kolestiramin",
    aliases: ["questran"],
    type: "drug",
    direction: "decrease",
    severity: "moderate",
    mechanism: "Bağırsak emilimini azaltır",
    note: "En az 4–6 saat arayla alın.",
  },
  {
    name: "St. John's Wort (Sarıkantaron)",
    aliases: ["st john", "sarı kantaron", "hypericum"],
    type: "drug",
    direction: "decrease",
    severity: "major",
    mechanism: "CYP3A4 ve P-gp indüktörü",
    note: "Bitkisel takviye; INR belirgin düşer. Varfarin kullanırken kesinlikle kaçının.",
  },
  {
    name: "Azatioprin",
    aliases: ["imuran"],
    type: "drug",
    direction: "decrease",
    severity: "moderate",
    mechanism: "Mekanizma belirsiz",
    note: "INR azalabilir; izlem önerilir.",
  },
  // ─── BESİNLER — INR AZALTANLAR (K vitamini) ──────────────────────
  {
    name: "Ispanak",
    aliases: ["spinach"],
    type: "food",
    direction: "decrease",
    severity: "major",
    mechanism: "Yüksek K vitamini (K1) içeriği",
    note: "Bir porsiyon (100 g) ~483 mcg K vitamini içerir. Tutarlı miktarda tüketin; tamamen kesmek zorunda değilsiniz.",
  },
  {
    name: "Lahana (kale/kara lahana)",
    aliases: ["kale", "kara lahana"],
    type: "food",
    direction: "decrease",
    severity: "major",
    mechanism: "Çok yüksek K vitamini (K1) içeriği",
    note: "100 g'da ~817 mcg K vitamini. Miktarı sabit tutun.",
  },
  {
    name: "Brokoli",
    aliases: [],
    type: "food",
    direction: "decrease",
    severity: "moderate",
    mechanism: "Orta-yüksek K vitamini içeriği",
    note: "100 g'da ~102 mcg K vitamini. Pişirme miktarı azaltabilir.",
  },
  {
    name: "Maydanoz",
    aliases: ["parsley"],
    type: "food",
    direction: "decrease",
    severity: "major",
    mechanism: "Çok yüksek K vitamini içeriği",
    note: "Çiğ olarak büyük miktarda tüketimden kaçının.",
  },
  {
    name: "Karnabahar",
    aliases: [],
    type: "food",
    direction: "decrease",
    severity: "moderate",
    mechanism: "Orta K vitamini içeriği",
    note: "Normal porsiyon genellikle sorun değil; aşırı miktardan kaçının.",
  },
  {
    name: "Brüksel lahanası",
    aliases: [],
    type: "food",
    direction: "decrease",
    severity: "moderate",
    mechanism: "Yüksek K vitamini içeriği",
    note: "Miktarı sabit tutun.",
  },
  {
    name: "Avokado",
    aliases: [],
    type: "food",
    direction: "decrease",
    severity: "moderate",
    mechanism: "K vitamini + muhtemelen CYP inhibisyonu",
    note: "Büyük miktarda tüketim INR'yi düşürebilir.",
  },
  {
    name: "Yeşil çay",
    aliases: ["green tea"],
    type: "food",
    direction: "decrease",
    severity: "minor",
    mechanism: "K vitamini içeriği",
    note: "Normal tüketim (1–2 fincan/gün) genellikle düşük risk. Büyük miktarda içeceklerden kaçının.",
  },
  // ─── BESİNLER — INR ARTTIRANLAR ──────────────────────────────────
  {
    name: "Greyfurt (Grapefruit)",
    aliases: ["grapefruit", "altıntop"],
    type: "food",
    direction: "increase",
    severity: "moderate",
    mechanism: "CYP3A4 inhibitörü (furanocoumarins)",
    note: "Taze greyfurt veya suyu INR'yi artırabilir. Düzenli tüketimden kaçının.",
  },
  {
    name: "Kızılcık (Cranberry)",
    aliases: ["cranberry", "kızılcık suyu"],
    type: "food",
    direction: "increase",
    severity: "moderate",
    mechanism: "CYP2C9 inhibisyonu",
    note: "Kızılcık suyu INR'yi artırabilir. Büyük miktarda içmekten kaçının.",
  },
  {
    name: "Sarımsak (yüksek doz takviye)",
    aliases: ["garlic"],
    type: "food",
    direction: "increase",
    severity: "minor",
    mechanism: "Antiplatelet etki + zayıf CYP inhibisyonu",
    note: "Normal mutfak kullanımı sorun değil; takviye kapsülleri (yüksek doz) kanamayı artırabilir.",
  },
  {
    name: "Zencefil (yüksek doz)",
    aliases: ["ginger"],
    type: "food",
    direction: "increase",
    severity: "minor",
    mechanism: "Antiplatelet etki",
    note: "Yemeklerdeki normal miktarda sorun olmaz; takviye/özütlerden kaçının.",
  },
  {
    name: "Mango",
    aliases: [],
    type: "food",
    direction: "increase",
    severity: "minor",
    mechanism: "K vitamini içerir ama CYP etkileşimi de olabilir",
    note: "Büyük miktarda tüketim INR'yi etkileyebilir; tutarlı tüketim önerilir.",
  },
  {
    name: "Balık yağı / Omega-3 (yüksek doz)",
    aliases: ["fish oil", "omega 3"],
    type: "food",
    direction: "increase",
    severity: "minor",
    mechanism: "Antiplatelet etki",
    note: "Yüksek doz takviye (>3 g/gün EPA+DHA) kanama riskini artırabilir.",
  },
  {
    name: "Alkol",
    aliases: ["içki", "bira", "şarap", "rakı"],
    type: "food",
    direction: "increase",
    severity: "moderate",
    mechanism: "Akut: CYP inhibisyonu; Kronik: CYP indüksiyonu",
    note: "Akut aşırı içki INR'yi artırır; kronik alkolizm düşürebilir. Karaciğer hasarı INR'yi artırır. Alkol tüketimini minimumda tutun.",
  },
];
